config/routes.rb
Rails.application.routes.draw do
  resources :wallets
  resources :cryptocurrencies, only: [:index, :show]
  resources :wallets, only: [:index, :show]

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show]
  resources :follows, only: [:new, :create]

  root 'cryptocurrencies#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :follows, foreign_key: :follower_id 
  has_many :cryptocurrencies, through: :follows, source: :followable, source_type: 'Cryptocurrency'
  
  has_many :wallets, through: :follows, source: :followable, source_type: 'Wallet'

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index 
        @users = User.all

        # # require 'httpclient'
        # # require 'json'

        # client = HTTPClient.new

        # response = client.get('https://chain.so/api/v2/get_info/DOGE')

        # if response.status_code == 200 then
        # # everything went swimmingly

        # content = JSON.parse response.content
        # @content = content

        # @name = "Name: "+content['data']['name']
        # @blocks = "Total Blocks: "+content['data']['blocks'].to_s

        # end
    end

    def show 
        @user = User.find(params[:id])
        @follows = @user.follows
        @cryptocurrencies = @user.cryptocurrencies 
        @wallets = @user.wallets
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_cryptocurrencies.html.erb
<div class = 'card'>
    <% @followed_currencies.each do |currency| %>
        <div class = 'card-content'>
            <p><%= currency.name %></p>
            <p><%= currency.symbol %></p>
        </div>
    <% end %>
</div>

app/views/users/index.html.erb
<div class = 'column is-one-quarter'>
column 1
<%= @name %>
</div>

<div class = 'column' >

<%= @blocks %>

column 2 
</div>

<div class = 'column is-one-quarter'>
column 3
<%= @content %>

</div>

app/views/users/show.html.erb
<div class = 'column is-half'>
    <div class = 'card is-centered'>
        <div class = 'card-header is-centered'>
            <p class = 'title is-4'>User: <%= @user.email %></p>
        </div>
        <% unless @cryptocurrencies.blank? %>
            <div class = 'card-content'>
                <p class = 'content' >Followed Currencies: <%= @cryptocurrencies.length %></p>
            </div>
            <div class = 'card-content'>
                <p class = 'content' >Followed Wallets: <%= @wallets.length %></p>
            </div>
            <div class = 'card-content'>
                <%#= render @cryptocurrencies %>
                <% @follows.each do |follow| %>
                    <%= follow.followable.class %>
                    <% if follow.followable.instance_of?(Wallet) %>
                        <p><%= follow.followable.address %> (<%=follow.followable.cryptocurrency.symbol%>)</p>
                    <% elsif follow.followable.instance_of?(Cryptocurrency) %>
                        <p><%= follow.followable.symbol %></p>
                            <% unless follow.followable.last_price.nil? %>
                                <p>Last price: $<%= follow.followable.last_price %> as of <%= follow.followable.last_price_date %></p>
                            <% end %>
                    <% end %>

                    <%#= link_to follow.followable, cryptocurrency_path(follow.followable) %>
                    <br />

                <% end %> 

                <%#= pluralize(@post.comments.length, "comment") %>
                
            </div>
        <% else %>

        <div class = 'card-content'> 
            <p class = 'content'>You havent followed any currencies =(</p>
            <%= link_to cryptocurrencies_path, "Cryptocurrencies" %>
        </div>

        <% end %>
            
    </div>
    <%#= render 'actions' %>
</div>