config/routes.rb
Rails.application.routes.draw do
  resources :wallets
  resources :cryptocurrencies, only: [:index, :show]
  resources :wallets, only: [:index, :show]

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show]
  resources :follows, only: [:new, :create]

  root 'cryptocurrencies#index'
end

app/models/wallet.rb
class Wallet < ApplicationRecord
    has_many :followers, as: :followable

    belongs_to :cryptocurrency
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  before_action :set_wallet, only: %i[ show edit update destroy ]

  # GET /wallets or /wallets.json
  def index
    @wallets = Wallet.all
    @follow = Follow.new
  end

  # GET /wallets/1 or /wallets/1.json
  def show


  end

  # GET /wallets/new
  def new
    @wallet = Wallet.new
  end

  # GET /wallets/1/edit
  def edit
  end

  # POST /wallets or /wallets.json
  def create
    @wallet = Wallet.new(wallet_params)

    respond_to do |format|
      if @wallet.save
        format.html { redirect_to @wallet, notice: "Wallet was successfully created." }
        format.json { render :show, status: :created, location: @wallet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wallet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wallets/1 or /wallets/1.json
  def update
    respond_to do |format|
      if @wallet.update(wallet_params)
        format.html { redirect_to @wallet, notice: "Wallet was successfully updated." }
        format.json { render :show, status: :ok, location: @wallet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wallet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wallets/1 or /wallets/1.json
  def destroy
    @wallet.destroy
    respond_to do |format|
      format.html { redirect_to wallets_url, notice: "Wallet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wallet
      @wallet = Wallet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wallet_params
      params.require(:wallet).permit(:address)
    end
end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/wallets/_form.html.erb
<%= form_with(model: wallet) do |form| %>
  <% if wallet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wallet.errors.count, "error") %> prohibited this wallet from being saved:</h2>

      <ul>
        <% wallet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      
    <%= form.label :name %>
    <%= form.text_field :name %>

    <%= form.label :address %>
    <%= form.text_field :address %>
    
    <%= form.label :cryptocurrency %>
    <%#= form.collection_select(:cryptocurrency, :cryptocurrency_id, Cryptocurrency.all, :id, :symbol_name, prompt: true ) %>
    <%#= form.select("cryptocurrency", "cryptocurrency_id", Cryptocurrency.all.collect{|c| [ c.name, c.id ]}) %>
    <%= form.collection_select :cryptocurrency_id, Cryptocurrency.order(:name),:id,:name, include_blank: true %>

  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wallets/edit.html.erb
<h1>Editing Wallet</h1>

<%= render 'form', wallet: @wallet %>

<%= link_to 'Show', @wallet %> |
<%= link_to 'Back', wallets_path %>

app/views/wallets/index.html.erb
<div class = 'card mt-4'>
  <p id="notice"><%= notice %></p>

  <h1>Wallets</h1>

  <table>
    <thead>
      <tr>
        <th>Address</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @wallets.each do |wallet| %>
        <tr>
          <td><%= wallet.cryptocurrency.symbol %></td>
          <td><%= wallet.address %></td>
          <td><%= link_to 'Show', wallet %></td>
          <td><%= link_to 'Edit', edit_wallet_path(wallet) %></td>
          <td><%= link_to 'Destroy', wallet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <%= form_with(model: @follow, url: follows_path, method: :post) do |f| %>
                  <%= f.hidden_field :follower_id, :value => current_user.id %>
                  <%= f.hidden_field :followable_type, :value => 'Wallet' %> 
                  <%= f.hidden_field :followable_id, :value => wallet.id %>  

                  <%= f.submit 'Follow' %>
              <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Wallet', new_wallet_path %>
</div>

app/views/wallets/new.html.erb
<div class = 'card mt-4'>
    <h1>New Wallet</h1>

    <%= render 'form', wallet: @wallet %>

    <%= link_to 'Back', wallets_path %>
</div>

app/views/wallets/show.html.erb
<div class = 'card mt-4'>
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Cryptocurrency:</strong>
    <%= @wallet.cryptocurrency.symbol %><br />
  </p>
  <p>
    <strong>Address:</strong>
    <%= @wallet.address %><br />
  </p>

  <%= link_to 'Edit', edit_wallet_path(@wallet) %> |
  <%= link_to 'Back', wallets_path %>
</div>