config/routes.rb
Rails.application.routes.draw do
  resources :wallets
  resources :cryptocurrencies, only: [:index, :show]
  resources :wallets, only: [:index, :show]

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show]
  resources :follows, only: [:new, :create]

  root 'cryptocurrencies#index'
end

app/models/cryptocurrency.rb
class Cryptocurrency < ApplicationRecord
    has_many :followers, as: :followable

    has_many :wallets
    def symbol_name 
        "#{Cryptocurrency.symbol} - name"
    end
end

app/controllers/cryptocurrencies_controller.rb
class CryptocurrenciesController < ApplicationController
  before_action :set_cryptocurrency, only: %i[ show edit update destroy ]

  # GET /cryptocurrencies or /cryptocurrencies.json
  def index
    @cryptocurrencies = Cryptocurrency.all
    @follow = Follow.new
  end

  # GET /cryptocurrencies/1 or /cryptocurrencies/1.json
  def show
    # @coin = params[:symbol]
    # @base_currency = params[:currency]
    @cryptocurrency = Cryptocurrency.find(params[:id])
    @coin = @cryptocurrency.symbol
    @base_currency = "USD"
        require 'httpclient'
        require 'json'

        client = HTTPClient.new #default_header: {"Accepts" => "application/json", 'X-CMC_PRO_API_KEY:' => 'b50921e9-ed4f-4cd7-9e9f-8a5de029f8f3' }

        query = {
          'convert' => 'USD', 
          'CMC_PRO_API_KEY' => 'b50921e9-ed4f-4cd7-9e9f-8a5de029f8f3', 
          'symbol' => "#{@coin}"
        }
        headers = ['Accepts: application/json', 'X-CMC_PRO_API_KEY: b50921e9-ed4f-4cd7-9e9f-8a5de029f8f3']
        # response = client.get('https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest', query)
        response = client.get('https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest', query)
        # response = client.get("https://chain.so//api/v2/get_price/#{@coin}/#{@base_currency}")

        if response.status_code == 200 then
        # everything went swimmingly

        content = JSON.parse response.content
        @content = content

        @price = content['data']["#{@coin}"]['quote']['USD']['price']

        #save the last checked price in the db so we dont have to do as many api calls.
        @cryptocurrency.last_price = @price 
        @cryptocurrency.last_price_date = Time.now
        @cryptocurrency.save

        # @price = content['data']['prices'][1]['price']
        # @name = "Name: "+content['data']['name']
        # @blocks = "Total Blocks: "+content['data']['blocks'].to_s
        @percent_change_1h = content['data']["#{@coin}"]['quote']['USD']['percent_change_1h']
        @percent_change_24h = content['data']["#{@coin}"]['quote']['USD']['percent_change_24h']
        @percent_change_7d = content['data']["#{@coin}"]['quote']['USD']['percent_change_7d']
        @percent_change_30d = content['data']["#{@coin}"]['quote']['USD']['percent_change_30d']
        @market_cap = content['data']["#{@coin}"]['quote']['USD']['market_cap']
        @volume_24h = content['data']["#{@coin}"]['quote']['USD']['volume_24h']

        else 
          # @error = response.error
          content = JSON.parse response.content
          @content = content
        end
  end

  # GET /cryptocurrencies/new
  def new
    @cryptocurrency = Cryptocurrency.new
  end

  # GET /cryptocurrencies/1/edit
  def edit
  end

  # POST /cryptocurrencies or /cryptocurrencies.json
  def create
    @cryptocurrency = Cryptocurrency.new(cryptocurrency_params)

    respond_to do |format|
      if @cryptocurrency.save
        format.html { redirect_to @cryptocurrency, notice: "Cryptocurrency was successfully created." }
        format.json { render :show, status: :created, location: @cryptocurrency }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cryptocurrency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cryptocurrencies/1 or /cryptocurrencies/1.json
  def update
    respond_to do |format|
      if @cryptocurrency.update(cryptocurrency_params)
        format.html { redirect_to @cryptocurrency, notice: "Cryptocurrency was successfully updated." }
        format.json { render :show, status: :ok, location: @cryptocurrency }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cryptocurrency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cryptocurrencies/1 or /cryptocurrencies/1.json
  def destroy
    @cryptocurrency.destroy
    respond_to do |format|
      format.html { redirect_to cryptocurrencies_url, notice: "Cryptocurrency was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cryptocurrency
      @cryptocurrency = Cryptocurrency.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cryptocurrency_params
      params.require(:cryptocurrency).permit(:name)
    end
end

app/helpers/cryptocurrencies_helper.rb
module CryptocurrenciesHelper
end

app/views/cryptocurrencies/index.html.erb
<div class = 'column is-centered'>
  <p id="notice"><%= notice %></p>

  <h1>Cryptocurrencies</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody class = 'table'>
      <% @cryptocurrencies.each do |cryptocurrency| %>
        <tr>

            <td><%= cryptocurrency.name %></td>
            <td><%= link_to 'Show', cryptocurrency %></td>
            <td><%#= link_to 'Follow', edit_cryptocurrency_path(cryptocurrency) %></td>
            <td>
            <% if current_user.cryptocurrencies.include? (cryptocurrency) %> 
              Already Following 
            <% else %>
              
              <%= form_with(model: @follow, url: follows_path, method: :post) do |f| %>
                          <%= f.hidden_field :follower_id, :value => current_user.id %>
                          <%= f.hidden_field :followable_type, :value => 'Cryptocurrency' %> 
                          <%= f.hidden_field :followable_id, :value => cryptocurrency.id %>  

                          <%= f.submit 'Follow' %>
                      <% end %>
            <% end %>
            </td>
            <% unless cryptocurrency.last_price.nil? %>
              <td>Last price: $<%= cryptocurrency.last_price %> (USD) as of <%= cryptocurrency.last_price_date %></td>
            <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

</div>

app/views/cryptocurrencies/show.html.erb
<div class = 'column'> 
<div class = 'card'> 
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @cryptocurrency.name %>
  </p>
  <p>
    <strong>Symbol:</strong>
    <%= @cryptocurrency.symbol %>
  </p>
  <p>
    <strong>Price:</strong>
    $<%= @price %> <%#= @base_currency %>
  </p>
    <strong>INFO:</strong>
    <table class = 'table'>
      <tr>
          <td>last hour change:<%= @percent_change_1h %>%</td>
      </tr>
      <tr>
          <td>last 24 hours change:<%= @percent_change_24h %>%</td>
      </tr>
      <tr>
          <td>last 7 days change:<%= @percent_change_7d %>%</td>
      </tr>
      <tr>
          <td>last 30 days change:<%= @percent_change_30d %>%</td>
      </tr>
      <tr>
          <td>market cap: $<%= number_with_delimiter(@market_cap, :delimiter => ',') %></td>
      </tr>
      <tr>
          <td>24 hour volume: $<%= number_with_delimiter(@volume_24h, :delimiter => ',') %></td>
      </tr>
    </table>

    <p>RAW: <%= @content %></p>

  <%= link_to 'Back', cryptocurrencies_path %>
</div>
</div>