config/routes.rb
Rails.application.routes.draw do
  resources :wallets
  resources :cryptocurrencies, only: [:index, :show]
  resources :wallets, only: [:index, :show]

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show]
  resources :follows, only: [:new, :create]

  root 'cryptocurrencies#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoDash</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar is-dark" role="navigation" aria-label="main navigation">
  <div class = 'navbar-brand'>
    <div class = 'navbar-item'>
      <b>CryptoDash - On Rails!</b>
    </div>
  </div>
  <div class="navbar-end">
    <div class = 'navbar-item'>
      <%= link_to 'Home', root_path, class: 'button is-link' %>
    </div>
    <% if current_user %>
      <div class = 'navbar-item'>
        <%= link_to 'Your Follows', user_path(current_user), class: 'button is-link' %>
      </div>
    <% end %>
    <div class = 'navbar-item'>
      <%= link_to 'Cryptocurrencies', cryptocurrencies_path, class: 'button is-link' %>
    </div>
    <div class = 'navbar-item'>
      <%= link_to 'Wallets', wallets_path, class: 'button is-link' %>
    </div>
    <div class="navbar-item">
      <div class="buttons">
        <% if current_user %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'button is-danger' %>
        <% else %>
          <%= link_to "Login", new_user_session_path, class: 'button is-link' %>
        <% end %>
      </div>
    </div>
  </div>
</nav>
<% flash.each do |type, msg| %>
  <div class = 'notification is-info'>
    <%= msg %>
  </div>
<% end %>
<div class = 'columns is-centered'>
      <%= yield %>
  

</div>
  </body>
</html>